# Generated by Django 4.2.7 on 2025-10-07 02:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de la planilla de recaudación', upload_to='planillas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('error', 'Error')], default='pending', help_text='Estado del procesamiento de la planilla', max_length=20)),
                ('datos_extraidos', models.JSONField(blank=True, help_text='Datos extraídos por Azure Form Recognizer', null=True)),
                ('error_procesamiento', models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falla', null=True)),
                ('nombre_archivo', models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255, null=True)),
                ('tamaño_archivo', models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Concepto de la tarifa (ej: Pasaje urbano, Pasaje interurbano)', max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de la tarifa', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de boletos vendidos')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal (precio × cantidad)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('planilla', models.ForeignKey(help_text='Planilla a la que pertenece esta tarifa', on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='api.planilla')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['concepto'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Concepto del ingreso', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del ingreso', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('planilla', models.ForeignKey(help_text='Planilla a la que pertenece este ingreso', on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='api.planilla')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['concepto'],
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Concepto del egreso', max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del egreso', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('planilla', models.ForeignKey(help_text='Planilla a la que pertenece este egreso', on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='api.planilla')),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['concepto'],
            },
        ),
        migrations.CreateModel(
            name='ControlBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inicial', models.PositiveIntegerField(help_text='Número inicial del talonario')),
                ('numero_final', models.PositiveIntegerField(help_text='Número final del talonario')),
                ('cantidad_vendidos', models.PositiveIntegerField(help_text='Cantidad de boletos vendidos')),
                ('cantidad_devueltos', models.PositiveIntegerField(default=0, help_text='Cantidad de boletos devueltos')),
                ('cantidad_anulados', models.PositiveIntegerField(default=0, help_text='Cantidad de boletos anulados')),
                ('total_boletos', models.PositiveIntegerField(help_text='Total de boletos en el talonario')),
                ('boletos_faltantes', models.PositiveIntegerField(default=0, help_text='Boletos faltantes (total - vendidos - devueltos - anulados)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('planilla', models.ForeignKey(help_text='Planilla a la que pertenece este control', on_delete=django.db.models.deletion.CASCADE, related_name='control_boletos', to='api.planilla')),
            ],
            options={
                'verbose_name': 'Control de Boleto',
                'verbose_name_plural': 'Controles de Boletos',
                'ordering': ['numero_inicial'],
            },
        ),
    ]
